# Use the official Golang image as the base image
FROM golang:1.24.2

# Set environment variables for Go build cache
ENV GOCACHE=/tmp/go-build
ENV GOPATH=/tmp/go

# Create cache directory with correct permissions
RUN mkdir -p ${GOCACHE} && chmod -R 777 /tmp

# Set the working directory inside the container
WORKDIR /app

# Copy the Go module files
COPY backend/go.mod backend/go.sum ./backend/
COPY test/go.mod test/go.sum ./test/

WORKDIR /app/backend
RUN go mod download

WORKDIR /app/test
RUN go mod download

WORKDIR /app

COPY . .

# Create a non-root user and group and set permissions
RUN groupadd -r nonroot && \
    useradd -r -g nonroot -d /app nonroot && \
    chown -R nonroot:nonroot /app

# Switch to the non-root user
USER nonroot

WORKDIR /app/test

# Run tests
CMD ["go", "test", "-v", "./..."]