name: Build, Test, and Push

on:
  workflow_dispatch:
  push:
    tags: ["v*"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ./app/go.sum
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run unit tests
        working-directory: ./app
        run: go test -v -mod=readonly ./...

  sonarcloud:
    needs: test  # Go on only if job "test" successfully
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.exclusions=**/*_test.go
            -Dsonar.projectKey=taekwondodev_go-gRPC-Authentication
            -Dsonar.organization=taekwondodev
            -Dsonar.coverage.exclusions=**/*
            -Dsonar.analysis.ignoreCoverage=true

  deploy:
    needs: sonarcloud  # Go on only if job "sonarcloud" successfully
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./app/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/go-grpc-auth:latest
            ghcr.io/${{ github.repository_owner }}/go-grpc-auth:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
